/**
 * This is a kingdee cosmic template project that is automatically generated by the Kingdee cosmic development assistant plugin. 
 * If there are any issues during the use process, you can provide feedback to the kingdee developer community website.
 * Website: https://developer.kingdee.com/developer?productLineId=29
 * Author: liebin.zheng
 * Generate Date: 2025-07-13 10:53:38
 */
package sxq0.cosmic.debug;

import kd.cosmic.debug.tools.CosmicLauncher;

/**
 * 启动本地应用程序(微服务节点)
 */
public class DebugApplication {
	
	

    public static void main(String[] args) {
    	
//    	Thread.currentThread().setContextClassLoader(new KDSecurityClassLoader(Thread.currentThread().getContextClassLoader()));
    	
        CosmicLauncher cosmic = new CosmicLauncher(false);

        cosmic.setClusterNumber("cosmic");
        cosmic.setTenantNumber("ierp");

        cosmic.setConfigUrl("127.0.0.1:2181?user=zookeeper&password=12345678");
//        cosmic.setConfigUrl("127.0.0.1:2181");
        
//        cosmic.setMcServerUrl("http://127.0.0.1:8090");
        cosmic.setMcServerUrl("http://127.0.0.1:8090/");
        cosmic.setWebResPath("D:/software/kingdee/cosimicStudioEnvForPeiXun/static-file-service");
        
//        cosmic.setFsServerUrl("127.0.0.1", 8100);
//        cosmic.setImageServerUrl("127.0.0.1", 8100);
        //当前服务是否消费mq消息，true表示消费消息，false不消费消息，默认false
        System.setProperty("mq.consumer.register", "true");

        //mq队列的唯一标识，这里XXX建议每个服务都不相同，一般上面的参数为true时这个参数必须加上
        System.setProperty("mq.debug.queue.tag", "ytj");
        cosmic.setStartWithQing(true);
        System.setProperty("qing.dpp.engine.localEmbed.enable","true");
        //自定义本地苍穹调试服务的端口
        cosmic.setCosmicWebPort(8881);
//        cosmic.set("domain.contextUrl","http://192.168.105.78:8881/ierp");
//        cosmic.setDubboConfig(false, true, true);
        cosmic.start();
        
        
    }
}